import {ILanguage} from "../../types/languageTypes";

const language: ILanguage = {
    ru:{
        craftTableStrings: {
            metrics: 'ед.',
            materialQuant: 'Использ. материал',
            subMatsQuant: 'Использ. доп. мат.',
            returnPercentage: 'Процент возврата',
            itemsOutput: 'Выход вещей',
            deleteButton: 'Удалить',
            materialTier: 'Тир',
            resQuant: 'Использ. ресурс',
            materialsOutput: 'Выход',
            alert: 'Расчетов нет.',
            unPerItem: 'ед. на предмет',
        },
        calculatorFormStrings: {
            resourceCraftHeader: 'Перекрафт ресурсов в материалы',
            itemsCraftHeader: 'Перекрафт материалов в экипировку',
            metrics: 'ед.',
            labelResourceAmount: 'Количество ресурса: ',
            labelItemsAmount: 'Количество материалов: ',
            labelOwnPercent: 'Свой процент: ',
            labelPercent: 'Процент возврата: ',
            percentError: 'Процент не может быть ниже 15,2% и выше 70%!',
            amountError: 'Количество материалов должно быть достаточным!',
            type: 'Тип: ',
            materialsOutput: 'Приблизительный выход материалов',
            itemsOutput: 'Приблизительный выход предметов',
            itemTier: 'Тир: ',
            craftListHeader: 'Предыдущие 10 расчетов',
            subMaterialsQuantity: 'Доп. материалы(если требуются)',
            copied: 'скопировано!',
        },
        infoTableStrings: {
            profitPerItem: 'Профит за предмет:',
            total: 'Итого:',
            noData: 'нет данных',
            from: ' из: ',
            item: 'Предмет',
            saleIn: 'Продажа в',
            un: 'ед.',
            tax: 'Плата за 100 еды:',
            taxPerOneItem: 'Налог за 1 предмет:',
            taxLabel: 'Налог:',
            journalLabel: 'Использовать журналы:',
            buyJournals: 'Купить пустые журналы в:',
            sellJournals: 'Продать полные журналы в:',
            journalQuantity: 'Журналов при крафте 1 предмета:',
            journalProfit: 'Профит от журналов при крафте 1 предмета:',
            errorNotification: 'Ошибка загрузки предметов!',
        },
        artefactsStrings: {
            sortLabel: 'Сортировать:',
            itemValueDescendingSelector: 'По убыванию ценности',
            itemValueAscendingSelector: 'По возрастанию ценности',
            itemValueTitle: 'ценность предмета: ',
            copyState: 'скопировано!',
            resetButtonTitle: 'Сброс маркера',
            value: 'Ценность:',
            city: 'Город:',
            price: 'Цена:',
            getArtefactsPrice: 'Обновить цену артефактов:',
            resetAllMarkers: 'Сброс всех маркеров:',
            artefactsTier: 'Тир артефактов:',
        },
        transportationFormStrings: {
            server: 'Сервер:',
            from: 'из:',
            albionWest: 'Западный Альбион (Вашингтон)',
            albionEast: 'Восточный Альбион (Сингапур)',
            into: 'в:',
            sortBy: 'Сортировать по:',
            percentageProfit: 'Прибыли в процентах',
            silverProfit: 'Прибыли в серебре',
            profitVolume: 'Прибыли в объеме',
            sortByLastChecked: 'Сортировка по последней проверкe:',
        },
        transportationListStrings: {
            requestError: 'Ошибка запроса, обновите страницу!',
            item: 'Предмет',
            itemName: 'Наименование',
            excludingTax: 'с вычетом налога',
            profit: 'Прибыль',
            percentageProfit: 'Прибыль в %',
            dailyTurnover: 'Суточный оборот',
        },
        backpackString: {
            gatherButton: 'Собрать',
            sortButton: 'Сортировать',
            iconTitle: 'Условное серебро. После выполненного крафта, который уведет балан в минус, и продажи которая принесет условный профит или убыток, можно будет наглядно посмотреть профитность крафтового цикла определенной вещи в игре.'
        },
        marketItemStings: {
            ownPriceLabel: 'Получить цену с сервера:',
            actionLabel: 'Действие:',
            sell: 'Продать',
            buy: 'Купить',
            amountLabel: 'Количество:',
            priceLabel: 'Цена:',
            totalPriceLabel: 'Всего:',
            tax: 'Налог на продажу 6.5%'
        },
        marketMenuStrings: {
            marketHeader: 'Рынок',
            sell: 'Продать',
            buy: 'Купить',
            alert: 'Ваш Рюкзак пуст.',
            search: 'Поиск'
        },
        GMItemSelectorStings: {
            dialogText: 'Здравствуйте! Поглядите на мой товар.',
            nutritionUsage1: 'Плата использования здания за потребленные',
            nutritionUsage2: '100 единиц еды:',
            search: 'Поиск',
        },
        GMCraftingFormStrings: {
            journalUsageButton: 'Использовать журналы:',
            journalInfoIconText: `Получить цену ОДНОГО журнала с сервера или ввести собственную цену.`,
            price: 'Цена:',
            quantity: 'Количество:',
            enchantment: 'Чары:',
            resourceLabel: 'Ресурсы:',
            returnRateLabel: 'Возврат ресурсов:',
            artefactLabel: 'Цена артефакта:',
            artefactInfoIconText: 'Получить цену ОДНОГО артефакта с сервера или ввести собственную цену. Цена всех артефактов:',
            totalPriceLabel: 'Цена в серебре:',
            foodTaxInfoIconText: 'Цены за станок с учетом зачарования.'
        },
    },
    en:{
        craftTableStrings: {
            metrics: ' un.',
            materialQuant: 'Mats. Quant.',
            subMatsQuant: 'Sub Mats. Quant.',
            returnPercentage: 'return %',
            itemsOutput: 'Items output',
            deleteButton: 'Delete',
            materialTier: 'Material tier',
            resQuant: 'Res. Quant.',
            materialsOutput: 'Mats output',
            alert: 'No calculations.',
            unPerItem: 'un. per item',
        },
        calculatorFormStrings: {
            resourceCraftHeader: 'Сrafting resources into materials',
            itemsCraftHeader: 'Сrafting materials into equipment',
            metrics: 'un.',
            labelResourceAmount: 'Resource quantity: ',
            labelItemsAmount: 'Materials quantity: ',
            labelOwnPercent: 'Your percentage: ',
            labelPercent: 'Return percentage: ',
            percentError: 'The percentage must be between 15,2% and 70%!',
            amountError: 'The initial quantity must be sufficient!',
            type: 'Type: ',
            materialsOutput: 'Approximate Product Output: ',
            itemsOutput: 'Approximate Items Output: ',
            itemTier: 'Tier: ',
            craftListHeader: 'Previous 10 calculations',
            subMaterialsQuantity: 'Required amount of sub materials: ',
            copied: 'copied!',
        },
        infoTableStrings: {
            profitPerItem: 'Profit per item:',
            total: 'Total:',
            noData: 'no data',
            from: ' from:',
            item: 'Item',
            saleIn: 'Sell in',
            un: 'un.',
            tax: 'Fee per 100 nutrition:',
            taxPerOneItem: 'Tax per 1 item:',
            taxLabel: 'Tax:',
            journalLabel: 'Use journals:',
            buyJournals: 'Buy empty journals in:',
            sellJournals: 'Sell full journals in:',
            journalQuantity: 'Journal quantity per 1 item crafted:',
            journalProfit: 'Journal profit per 1 item crafted:',
            errorNotification: 'Error loading items!',
        },
        artefactsStrings: {
            sortLabel: 'Sort:',
            itemValueDescendingSelector: 'Descending item value',
            itemValueAscendingSelector: 'Ascending item value',
            itemValueTitle: 'item value: ',
            copyState: 'copied!',
            resetButtonTitle: 'Marker reset',
            value: 'Value:',
            city: 'City:',
            price: 'Price:',
            getArtefactsPrice: 'Update artefacts prices:',
            resetAllMarkers: 'Reset all markers:',
            artefactsTier: 'Artefacts tier:',
        },
        transportationFormStrings: {
            server: 'Server:',
            from: 'from:',
            albionWest: 'Albion West(Washington DC)',
            albionEast: 'Albion East(Singapore)',
            into: 'into:',
            sortBy: 'Sort by:',
            percentageProfit: 'Percentage profit',
            silverProfit: 'Profit',
            profitVolume: 'Profit volume',
            sortByLastChecked: 'Sort by last checked:',
        },
        transportationListStrings: {
            requestError: 'Request error, please refresh the page!',
            item: 'Item',
            itemName: 'Item Name',
            excludingTax: 'excluding tax',
            profit: 'Profit',
            percentageProfit: 'Percentage profit',
            dailyTurnover: 'Daily turnover',
        },
        backpackString: {
            gatherButton: 'Stack',
            sortButton: 'Sort',
            iconTitle: 'Conditional silver. After completing the craft, which will take the balance into the red, and the sale, which will bring a conditional profit or loss, it will be possible to visually see the profitability of the crafting cycle of a certain item in the game.'
        },
        marketItemStings: {
            ownPriceLabel: 'Get price from server:',
            actionLabel: 'Action:',
            sell: 'Sell',
            buy: 'Buy',
            amountLabel: 'Amount:',
            priceLabel: 'Price:',
            totalPriceLabel: 'Total:',
            tax: 'Sales tax 6.5%'
        },
        marketMenuStrings: {
            marketHeader: 'Marketplace',
            sell: 'Sell',
            buy: 'Buy',
            alert: 'Your inventory is empty.',
            search: 'Search'
        },
        GMItemSelectorStings: {
            dialogText: 'Hello traveler, come closer and have a look.',
            nutritionUsage1: 'Usage fee per 100 Nutrition',
            nutritionUsage2: 'consumed:',
            search: 'Search'
        },
        GMCraftingFormStrings: {
            journalUsageButton: 'Use journals:',
            journalInfoIconText: `Get the price of ONE journal from the server or enter your own price.`,
            quantity: 'Quantity:',
            price: 'Price:',
            enchantment: 'Enchantment:',
            resourceLabel: 'Resources:',
            returnRateLabel: 'Resource Return Rate:',
            artefactLabel: 'Artefact\'s price:',
            artefactInfoIconText: 'Get the price of ONE artefact from the server or enter your own price. Price of all artifacts:',
            totalPriceLabel: 'Silver Cost:',
            foodTaxInfoIconText: 'Food tax including enchantment.',
        },
    }
};
export default language;
