import {TConsumable} from "../../types/consumableTypes";

export const potionItems: TConsumable = [
    {
        itemId: 'T4_POTION_HEAL',
        amountCrafted: 5,
        foodConsumption: 135,
        T4_BURDOCK: 24,
        T3_EGG: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T4_POTION_ENERGY',
        amountCrafted: 5,
        foodConsumption: 135,
        T4_BURDOCK: 24,
        T4_MILK: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T4_POTION_COOLDOWN',
        amountCrafted: 5,
        foodConsumption: 54,
        T4_BURDOCK: 8,
        T3_COMFREY: 4,
        T1_ALCHEMY_EXTRACT_LEVEL: 5,

    },
    {
        itemId: 'T4_POTION_BERSERK',
        amountCrafted: 10,
        foodConsumption: 72,
        T3_ALCHEMY_RARE_WEREWOLF: 1,
        T4_BURDOCK: 16,
        T1_ALCHEMY_EXTRACT_LEVEL: 10,
    },
    {
        itemId: 'T4_POTION_LAVA',
        amountCrafted: 10,
        foodConsumption: 72,
        T3_ALCHEMY_RARE_IMP: 1,
        T4_MILK: 16,
        T1_ALCHEMY_EXTRACT_LEVEL: 10,
    },
    {
        itemId: 'T4_POTION_GATHER',
        amountCrafted: 10,
        foodConsumption: 72,
        T3_ALCHEMY_RARE_ELEMENTAL: 1,
        T4_BUTTER: 16,
        T1_ALCHEMY_EXTRACT_LEVEL: 10,

    },
    {
        itemId: 'T4_POTION_TORNADO',
        amountCrafted: 10,
        foodConsumption: 72,
        T3_ALCHEMY_RARE_EAGLE: 1,
        T4_BURDOCK: 16,
        T1_ALCHEMY_EXTRACT_LEVEL: 10,
    },
    {
        itemId: 'T5_POTION_REVIVE',
        amountCrafted: 5,
        foodConsumption: 189,
        T5_TEASEL: 24,
        T4_BURDOCK: 12,
        T5_EGG: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T5_POTION_STONESKIN',
        amountCrafted: 5,
        foodConsumption: 189,
        T5_TEASEL: 24,
        T4_BURDOCK: 12,
        T4_MILK: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T5_POTION_SLOWFIELD',
        amountCrafted: 5,
        foodConsumption: 189,
        T5_TEASEL: 24,
        T4_BURDOCK: 12,
        T5_EGG: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T5_POTION_MOB_RESET',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_PANTHER: 1,
        T5_TEASEL: 48,
        T4_BURDOCK: 24,
        T2_AGARIC: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T5_POTION_CLEANSE2',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_ENT: 1,
        T5_TEASEL: 48,
        T3_COMFREY: 24,
        T4_BUTTER: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T5_POTION_ACID',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_DIREBEAR: 1,
        T5_TEASEL: 48,
        T4_BURDOCK: 24,
        T4_MILK: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T6_POTION_HEAL',
        amountCrafted: 5,
        foodConsumption: 486,
        T6_FOXGLOVE: 72,
        T5_EGG: 18,
        T6_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T6_POTION_ENERGY',
        amountCrafted: 5,
        foodConsumption: 486,
        T6_FOXGLOVE: 72,
        T6_MILK: 18,
        T6_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T6_POTION_COOLDOWN',
        amountCrafted: 5,
        foodConsumption: 243,
        T6_FOXGLOVE: 24,
        T5_TEASEL: 12,
        T3_COMFREY: 12,
        T6_MILK: 6,
        T1_ALCHEMY_EXTRACT_LEVEL: 15,
    },
    {
        itemId: 'T6_POTION_BERSERK',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_WEREWOLF: 1,
        T6_FOXGLOVE: 48,
        T2_AGARIC: 24,
        T6_ALCOHOL: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T6_POTION_LAVA',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_IMP: 1,
        T6_MILK: 48,
        T6_FOXGLOVE: 24,
        T3_EGG: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T6_POTION_GATHER',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_ELEMENTAL: 1,
        T6_BUTTER: 48,
        T6_FOXGLOVE: 24,
        T5_TEASEL: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T6_POTION_TORNADO',
        amountCrafted: 10,
        foodConsumption: 378,
        T5_ALCHEMY_RARE_EAGLE: 1,
        T6_FOXGLOVE: 48,
        T5_TEASEL: 24,
        T3_EGG: 12,
        T1_ALCHEMY_EXTRACT_LEVEL: 30,
    },
    {
        itemId: 'T7_POTION_REVIVE',
        amountCrafted: 5,
        foodConsumption: 648,
        T7_MULLEIN: 72,
        T6_FOXGLOVE: 36,
        T5_EGG: 18,
        T7_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T7_POTION_STONESKIN',
        amountCrafted: 5,
        foodConsumption: 810,
        T7_MULLEIN: 72,
        T6_FOXGLOVE: 36,
        T4_BURDOCK: 36,
        T6_MILK: 18,
        T7_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T7_POTION_SLOWFIELD',
        amountCrafted: 5,
        foodConsumption: 810,
        T7_MULLEIN: 72,
        T6_FOXGLOVE: 36,
        T4_BURDOCK: 36,
        T5_EGG: 18,
        T7_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T7_POTION_MOB_RESET',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_PANTHER: 1,
        T7_MULLEIN: 144,
        T6_FOXGLOVE: 72,
        T3_COMFREY: 72,
        T2_AGARIC: 36,
        T7_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T7_POTION_CLEANSE2',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_ENT: 1,
        T7_MULLEIN: 144,
        T4_BURDOCK: 72,
        T3_COMFREY: 72,
        T6_BUTTER: 36,
        T7_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T7_POTION_ACID',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_DIREBEAR: 1,
        T7_MULLEIN: 144,
        T6_FOXGLOVE: 72,
        T6_ALCOHOL: 72,
        T6_MILK: 36,
        T7_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T8_POTION_COOLDOWN',
        amountCrafted: 5,
        foodConsumption: 810,
        T8_YARROW: 72,
        T7_MULLEIN: 36,
        T5_TEASEL: 36,
        T8_MILK: 18,
        T8_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T8_POTION_CLEANSE',
        amountCrafted: 5,
        foodConsumption: 810,
        T8_YARROW: 72,
        T7_MULLEIN: 36,
        T5_TEASEL: 36,
        T8_MILK: 18,
        T8_ALCOHOL: 18,
        T1_ALCHEMY_EXTRACT_LEVEL: 45,
    },
    {
        itemId: 'T8_POTION_BERSERK',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_WEREWOLF: 1,
        T8_YARROW: 144,
        T3_COMFREY: 72,
        T6_ALCOHOL: 72,
        T7_ALCOHOL: 36,
        T8_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T8_POTION_LAVA',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_IMP: 1,
        T8_MILK: 144,
        T8_YARROW: 72,
        T7_MULLEIN: 72,
        T5_EGG: 36,
        T8_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T8_POTION_GATHER',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_ELEMENTAL: 1,
        T8_BUTTER: 144,
        T8_YARROW: 72,
        T7_MULLEIN: 72,
        T6_FOXGLOVE: 36,
        T8_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
    {
        itemId: 'T8_POTION_TORNADO',
        amountCrafted: 10,
        foodConsumption: 1620,
        T7_ALCHEMY_RARE_EAGLE: 1,
        T8_YARROW: 144,
        T7_MULLEIN: 72,
        T7_ALCOHOL: 72,
        T5_EGG: 36,
        T8_ALCOHOL: 36,
        T1_ALCHEMY_EXTRACT_LEVEL: 90,
    },
]